/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFyMsskfkfk+dc= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFyMsskfkfk+dc= >>
// ----------- >>
public class Alumno {
    // ----------- << attribute.annotations@AAAAAAFyMstJb0gOGfg= >>
    // ----------- >>
    private int idAlumno;

    // ----------- << attribute.annotations@AAAAAAFyMstwEEgVma8= >>
    // ----------- >>
    private String nombreAlumno;

    // ----------- << attribute.annotations@AAAAAAFyMsxwbkh411g= >>
    // ----------- >>
    private Universidad ;

    public int getIdAlumno() {
        return idAlumno;
    }

    public String getNombreAlumno() {
        return nombreAlumno;
    }

    public Universidad get() {
        return ;
    }

    public void setIdAlumno(int idAlumno) {
        this.idAlumno = idAlumno;
    }

    public void setNombreAlumno(String nombreAlumno) {
        this.nombreAlumno = nombreAlumno;
    }

    public void set(Universidad ) {
        this. = ;
    }

    public void link(Universidad _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAFyMsvDZkgd6gM= >>
    // ----------- >>
    public void Crear() {
    // ----------- << method.body@AAAAAAFyMsvDZkgd6gM= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMsvq/kgkBCc= >>
    // ----------- >>
    public void Modificar() {
    // ----------- << method.body@AAAAAAFyMsvq/kgkBCc= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMswDM0gr+B4= >>
    // ----------- >>
    public void Eliminar() {
    // ----------- << method.body@AAAAAAFyMswDM0gr+B4= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFyMsskfkfk+dc= >>
// ----------- >>
}