/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFyMsWCdUZyZ5E= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFyMsWCdUZyZ5E= >>
// ----------- >>
public class Profesor {
    // ----------- << attribute.annotations@AAAAAAFyMsYcukadZSY= >>
    // ----------- >>
    private int idProfesor;

    // ----------- << attribute.annotations@AAAAAAFyMsZ6J0akvgs= >>
    // ----------- >>
    private String nombreProfesor;

    // ----------- << attribute.annotations@AAAAAAFyMsxOo0g1F3s= >>
    // ----------- >>
    private Universidad ;

    public int getIdProfesor() {
        return idProfesor;
    }

    public String getNombreProfesor() {
        return nombreProfesor;
    }

    public Universidad get() {
        return ;
    }

    public void setIdProfesor(int idProfesor) {
        this.idProfesor = idProfesor;
    }

    public void setNombreProfesor(String nombreProfesor) {
        this.nombreProfesor = nombreProfesor;
    }

    public void set(Universidad ) {
        this. = ;
    }

    public void link(Universidad _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAFyMscxyUas7/I= >>
    // ----------- >>
    public void Crear() {
    // ----------- << method.body@AAAAAAFyMscxyUas7/I= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMsdrokazbDI= >>
    // ----------- >>
    public void Modificar() {
    // ----------- << method.body@AAAAAAFyMsdrokazbDI= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMsePlEa6T4A= >>
    // ----------- >>
    public void Eliminar() {
    // ----------- << method.body@AAAAAAFyMsePlEa6T4A= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFyMsWCdUZyZ5E= >>
// ----------- >>
}