/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package package1;

import java.util.*;
import java.time.*;



// ----------- << imports@AAAAAAFyMsm1C0eUdLs= >>
// ----------- >>

// ----------- << class.annotations@AAAAAAFyMsm1C0eUdLs= >>
// ----------- >>
public class Universidad {
    // ----------- << attribute.annotations@AAAAAAFyMsnV7Ue+Wjs= >>
    // ----------- >>
    private int idUniversidad;

    // ----------- << attribute.annotations@AAAAAAFyMso2t0fGk5o= >>
    // ----------- >>
    private String nombreUniversidad;

    // ----------- << attribute.annotations@AAAAAAFyMsxOo0g0UEE= >>
    // ----------- >>
    private Profesor ;

    // ----------- << attribute.annotations@AAAAAAFyMsxwbkh3hOU= >>
    // ----------- >>
    private Alumno ;

    public int getIdUniversidad() {
        return idUniversidad;
    }

    public String getNombreUniversidad() {
        return nombreUniversidad;
    }

    public Profesor get() {
        return ;
    }

    public Alumno get() {
        return ;
    }

    public void setIdUniversidad(int idUniversidad) {
        this.idUniversidad = idUniversidad;
    }

    public void setNombreUniversidad(String nombreUniversidad) {
        this.nombreUniversidad = nombreUniversidad;
    }

    public void set(Profesor ) {
        this. = ;
    }

    public void set(Alumno ) {
        this. = ;
    }

    public void link(Profesor _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void link(Alumno _) {
        if (_ != null) {
            _.unlink();
            _.set(this);
        }

        unlink();
        set(_);
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    public void unlink() {
        if (get() != null) {
            get().set(null);
            set(null);
        }
    }

    // ----------- << method.annotations@AAAAAAFyMsqq7EfPl6E= >>
    // ----------- >>
    public void Crear() {
    // ----------- << method.body@AAAAAAFyMsqq7EfPl6E= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMsrLlkfWEHU= >>
    // ----------- >>
    public void Modificar() {
    // ----------- << method.body@AAAAAAFyMsrLlkfWEHU= >>
    // ----------- >>
    }
    // ----------- << method.annotations@AAAAAAFyMsrxs0fdjwQ= >>
    // ----------- >>
    public void Eliminar() {
    // ----------- << method.body@AAAAAAFyMsrxs0fdjwQ= >>
    // ----------- >>
    }
// ----------- << class.extras@AAAAAAFyMsm1C0eUdLs= >>
// ----------- >>
}