CREATE TABLE SOCIO
(
    COD_SOCIO INT NOT NULL,
    NOMBRE VARCHAR(30) NOT NULL,
    APELLIDO1 VARCHAR(30) NOT NULL,
    APELLIDO2 VARCHAR(30),
    DNI CHAR(9) UNIQUE,
    FECHA_NAC DATE NOT NULL,
    FECHA_ALTA DATE DEFAULT CURRENT_DATE,
    CONSTRAINT  PK_SOCIO PRIMARY KEY (COD_SOCIO),
    CONSTRAINT  FECHA_NAC CHECK (AGE(FECHA_NAC) > '18years')
);

CREATE TABLE TIPO
(
    COD_TIPO INT NOT NULL,
    NOM_TIPO VARCHAR(30) NOT NULL,
    CONSTRAINT  PK_TIPO PRIMARY KEY (COD_TIPO)
);

CREATE TABLE TELEFONO
(
    COD_TELF INT NOT NULL,
    NUM_TELF VARCHAR(20) NOT NULL,
    COD_TIPO INT NOT NULL,
    CONSTRAINT  PK_TELF PRIMARY KEY (COD_TELF),
    CONSTRAINT  FK_TELF FOREIGN KEY (COD_TIPO)
    REFERENCES  TIPO (COD_TIPO)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE TABLE TELF_SOCIO
(
    COD_SOCIO INT NOT NULL,
    COD_TELF INT NOT NULL,
    CONSTRAINT  PK_TELFSOCIO PRIMARY KEY (COD_SOCIO, COD_TELF),
    CONSTRAINT  FK_TELFSOCIO_SOCIO FOREIGN KEY (COD_SOCIO)
    REFERENCES  SOCIO (COD_SOCIO)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
    CONSTRAINT  FK_TELFSOCIO_TELF FOREIGN KEY (COD_TELF)
    REFERENCES TELEFONO (COD_TELF)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);